### ISSUE TITLE
TimeFeatureNode  unsupported operand type(s) for /: 'int' and 'str'

### ISSUE THREAD

**Issue by Bookwald** [ryanontheinside/ComfyUI_RyanOnTheInside#11]
I can't get TimeFeatureNode to work in Depth Chamber workflow. Other nodes like ColorFeature work fine. I replaced Time with Color to get the workflow to complete.

**Comment by ryanontheinside** [comment]
Try just recreating the time feature node and it will probably work. Workflows have no versioning, they break a lot.
