### ISSUE TITLE
The error message I encountered while loading audio

### ISSUE THREAD

**Issue by loverelic0211** [ryanontheinside/ComfyUI_RyanOnTheInside#13]
Prompt outputs failed validation: Return type mismatch between linked nodes: audio, AUDIO != VHS_AUDIO
AudioSeparator:
- Return type mismatch between linked nodes: audio, VHS_AUDIO != AUDIO
VHS_VideoCombine:
- Return type mismatch between linked nodes: audio, AUDIO != VHS_AUDIO

**Comment by ryanontheinside** [comment]
Based on this information I can't tell exactly what's going on, but I would recommend updating comfyui and these nodes
