### ISSUE TITLE
unmix loading problem

### ISSUE THREAD

**Issue by Sickdooc** [ryanontheinside/ComfyUI_RyanOnTheInside#19]
I sincerely appreciate the author's selfless sharing. During my attempts, I encountered an error with the unmix download and load node, indicating that the correct download address and save path may not have been referenced. Could you please advise me on how to resolve the issue? I sincerely appreciate your assistance!
![20241112135924](https://github.com/user-attachments/assets/e63e5647-5ded-408d-8783-ceec1a697d84)

**Comment by ryanontheinside** [comment]
hey no prob

you can download the models [manually from here](https://sigsep.github.io/open-unmix/#%F0%9F%8F%81-getting-started) 
![image](https://github.com/user-attachments/assets/30868ad1-8ee9-4aac-9344-8379d9dd3f71)

and place them under models/openunmix as follows
![image](https://github.com/user-attachments/assets/2dcadf73-8d16-443a-9337-67731c5766c8)

**Comment by Sickdooc** [comment]
But each version contains drums\bass\vocals\other4.pth. Not an overall “umxl.pth” as shown in your screenshot. I would appreciate any further clarification.

**Comment by diamond-one** [comment]
@Sickdooc
You're right.

I pulled out the node’s download function so the models can be created directly from the command line.

---

### Steps to get Open-Unmix models for this node

1. Open a terminal in your ComfyUI environment

2. Run:

```bash
python -c "import torch; m=torch.hub.load('sigsep/open-unmix-pytorch','umxhq',device='cpu', trust_repo=True); torch.save(m.state_dict(), 'ComfyUI/models/openunmix/umxhq.pth')"
```

```bash
python -c "import torch; m=torch.hub.load('sigsep/open-unmix-pytorch','umxl',device='cpu', trust_repo=True); torch.save(m.state_dict(), 'ComfyUI/models/openunmix/umxl.pth')"
```

```bash
python -c "import torch; m=torch.hub.load('sigsep/open-unmix-pytorch','umxse',device='cpu', trust_repo=True); torch.save(m.state_dict(), 'umxse.pth')"
```

---

### Important

* Do **not** download models from Zenodo manually
* This node expects a **single merged `.pth` file**, not the 4 separate weight files

---

### Result

```
ComfyUI/models/openunmix/
    umxhq.pth
    umxl.pth
    umxse.pth

```
