### ISSUE TITLE
fatal: unable to auto-detect email address

### ISSUE THREAD

**Issue by lunatico67** [ryanontheinside/ComfyUI_RyanOnTheInside#26]
Hi
when I try to update the custom node:

Microsoft Windows [Version 10.0.22631.4460]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside>git pull
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'susana@luna.(none)')

C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_RyanOnTheInside>

--- Please; How can I solve it?

**Comment by ryanontheinside** [comment]
Hi there, this has to do with your Git configuration, and not the nodes. You can run the commands detailed in the error  message to configure your git credentials, though I am not sure why its asking you to do that just to pull from the repo.

Instead, if you're able, I would recommend updating the nodes through the ComfyUI Manager menu.

**Comment by lunatico67** [comment]
Thanks for the help ryan.
I will try it
