### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by kp666** [ryanontheinside/ComfyUI_RyanOnTheInside#5]
[proximity_particle.json](https://github.com/user-attachments/files/17012864/proximity_particle.json)
https://civitai.com/user/ryanontheinside/models
these only work on commit hash 466b4c2407e8d2d69fa4f46dc0ab4d02b7de3247
On main these break with failed to load module. Should I do anything to migrate to main?

![image](https://github.com/user-attachments/assets/cb99c990-f2a8-4dd7-ab01-2c6bbf8ea9b1)

**Comment by ryanontheinside** [comment]
this is my bad, fixing

**Comment by ryanontheinside** [comment]
Should be good lmk

**Comment by kp666** [comment]
works.
