### ISSUE TITLE
Error with MIDI

### ISSUE THREAD

**Issue by kuzman123** [ryanontheinside/ComfyUI_RyanOnTheInside#7]
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python3101\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python3101\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
got prompt
Failed to validate prompt for output 180:
* MIDILoadAndExtract 190:
  - Exception when validating inner node: module 'folder_paths' has no attribute 'exists_and_is_file'
Output will be ignored
Loading model from: C:\comf\ComfyUI\models\openunmix\umxl.pth
Using cache found in C:\Users\Kuzma/.cache\torch\hub\sigsep_open-unmix-pytorch_master
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python3101\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python3101\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Prompt executed in 5.85 seconds

**Comment by ryanontheinside** [comment]
kuzman! Thank you SO much for your interest in my nodes, especially in the MIDI functionality!!!! I have been waiting for someone specifically interested in the MIDI keyboard.

That being said, I have become extremely busy over the last week so I can't fix this at the moment but I hope to be able to in the coming week. Hopefully you'll be willing to give it another shot then! The same applies to the other issue you opened - I really appreciate the feedback but I'll need to come back to it.

Thanks again!!

**Comment by kuzman123** [comment]
Hey Ryan, no prob, i will be here hopefully. I'm really interested to make that feature working, cause that will open Pandora's box

**Comment by ryanontheinside** [comment]
KUZMAN

should be fixed lmk!
